apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: pluto
  labels:
    app: plt-6cc-api
spec:
  containers:
  - name: nginx
    image: nginx:1.17.3-alpine
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80