apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim
  namespace: earth
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi