apiVersion: v1
kind: Service
metadata:
  
  name: project-plt-6cc-svc
  namespace: pluto
spec:
  type: ClusterIP
  ports:
  - name: tcp
    port: 3333
    protocol: TCP
    targetPort: 80
  selector:
    app: plt-6cc-api